### PR TITLE
Changes and rework for pac4j 5

### LINKED ISSUE #151: Support Pac4j 5
When booting this with Pac4J 5, we're getting `org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: 'java.lang.Object org.pac4j.core.engine.SecurityLogic.perform`

### PR DESCRIPTION
**Pull request by SiMiKohl**
- Changed pac4j to 5.3.1
- Changed to Java 11 and (optional) servlet-api 4
- Changed jersey in jersey-pac4j back to 2.35
- Copied tests to jersey228-pac4j
- "Reworked" dependencies-management
- Switched to jakarta-artifacts
- Added .fbExcludeFilterFile to .gitignore

Mainly tested with jersey 2.35, Closes #151

### CODE REVIEW

**Comment by leleuj** [comment]
Thanks for this great contribution. I will review it ASAP.

File: core/src/main/java/org/pac4j/jax/rs/pac4j/JaxRsContext.java [hunk 1]
```diff
@@ -44,20 +49,24 @@
...
-
     private final Providers providers;
 
     private ResponseBuilder abortResponse = null;
 
     private MultivaluedMap<String, String> parameters = null;
 
+    private SessionStore sessionStore = null;
+
     public JaxRsContext(Providers providers, ContainerRequestContext requestContext, SessionStore sessionStore) {
```
Comment (leleuj) [inline core/src/main/java/org/pac4j/jax/rs/pac4j/JaxRsContext.java:60]: The `sessionStore` should not be used to create the `JaxRsContext`. Both should be treated separately.

File: core/src/main/java/org/pac4j/jax/rs/pac4j/JaxRsProfileManager.java [hunk 2]
```diff
@@ -7,27 +7,31 @@
...
+        super(context, sessionStore);
     }
 
-    @Override
-    public void logout() {
-        super.logout();
-
-        new RequestPac4JSecurityContext((JaxRsContext) this.context).context().ifPresent(c -> c.principal = null);
-    }
+//    @Override
```
Comment (leleuj) [inline core/src/main/java/org/pac4j/jax/rs/pac4j/JaxRsProfileManager.java:29]: To be removed, `logout` no longer exists in the `ProfileManager`. It was too confusing.

File: jersey228/src/main/java/org/pac4j/jax/rs/grizzly/pac4j/GrizzlyJaxRsContext.java [hunk 3]
```diff
@@ -22,8 +25,8 @@
 
     private final Request request;
 
-    public GrizzlyJaxRsContext(Providers providers, ContainerRequestContext requestContext,
-            SessionStore sessionStore, Request request) {
+    public GrizzlyJaxRsContext(Providers providers, ContainerRequestContext requestContext, SessionStore sessionStore,
```
Comment (leleuj) [inline jersey228/src/main/java/org/pac4j/jax/rs/grizzly/pac4j/GrizzlyJaxRsContext.java:28]: Same feedback as for the `JaxRsContent`. The `SessionStore` should be treated separately.

**Review by leleuj — COMMENTED** [review]
LGTM

My main concern is the separation between the `SessionStore` and the web contexts. I hope this is feasible.

**Comment by leleuj** [comment]
@SiMiKohl I replaced the Travis build (disabled) by the Github Actions build and reverted the versions to the latest stable release. The master version is now 5.0.0-SNAPSHOT.

Can you sync with master? Thx

File: core/src/main/java/org/pac4j/jax/rs/pac4j/JaxRsContext.java (hunk 1 above)
Comment (SiMiKohl) [reply core/src/main/java/org/pac4j/jax/rs/pac4j/JaxRsContext.java:60]: This is exactly how I see it. The reason why this was initially implemented this way (not by me) is that the Context is the only implementation-specific object that is available within the filters of the core project. I have already modified this so that the SessionStore is not needed in the constructor, but is determined by the context and the config from the providers. The only other alternatives would be to make the filters implementation-specific, to register the SessionStores as providers or to rely on the SessionStores from the Config. However, this would possibly break the compatibility.

Comment (leleuj) [reply core/src/main/java/org/pac4j/jax/rs/pac4j/JaxRsContext.java:60]: I don't know this implementation enough, but for sure, we can break the compatibility as it's a major version.
So if you have a better solution to properly separate the session store from the context, go ahead.

**Comment by SiMiKohl** [comment]
As discussed, I have separated the SessionStore from the Context. For this I added a new provider for each implementation. Additionally I added implementation specific features which registers all needed providers by themselves. This simplifies the usage and allows an easier modification/extension. Furthermore I changed the SessionStores to Singeltons.

**Comment by leleuj** [comment]
Excellent! Merging. Will release as soon as you confirm that everything is ok...

**Comment by leleuj** [comment]
OK. Good. Go ahead and keep me posted when the release is needed.

**Comment by SiMiKohl** [comment]
Just a short feedback: I´m going to update my PR next week with an update to pac4j 5.4 and an version for resteasy3 and resteasy5

**Comment by jhauglid** [comment]
What is the status on this pull request? It would be nice to be able to move to pac4j 5.

**Comment by leleuj** [comment]
I think we still have some pending updates coming: @SiMiKohl ?

I can release at any time.

**Comment by SiMiKohl** [comment]
Based on https://github.com/pac4j/jax-rs-pac4j/pull/281, I currently have no other additions. I think a release (and the needed modifications in the wiki) could be performed. The only open topic is the development of versions for JakartaEE 9/Jakarta RESTful Web Services 3.0 and onwards. Unfortunately I don't have time for this at the moment, but will look into it as soon as possible.

**Comment by leleuj** [comment]
I just released jax-rs-pac4j v5.0.0. It will show up in the central Maven repository within a few minutes/hours.

One thing we could maybe fix is the log4j dependency which has security issues in the internal Github security report. Can we remove it?

**Comment by SiMiKohl** [comment]
Actually, there is no direct dependency to log4j. However, there are two dependencyManagement entries. The one from the parent-pom could indeed be removed. Unfortunately the entry from the pom of resteasy5-pac4j is necessary to satisfy the enforcer-plugin. Here otherwise the log4j-api would come as a provided dependency in different versions by resteasy5 itself (see below). But we could probably just update to the latest version.

```
Dependency convergence error for org.apache.logging.log4j:log4j-api:jar:2.17.1:provided paths to dependency are:
+-org.pac4j:resteasy5-pac4j:jar:5.0.1-SNAPSHOT
  +-org.jboss.resteasy:resteasy-core:jar:5.0.3.Final:provided
    +-org.jboss.logging:jboss-logging:jar:3.4.3.Final:provided
      +-org.apache.logging.log4j:log4j-api:jar:2.17.1:provided
and
+-org.pac4j:resteasy5-pac4j:jar:5.0.1-SNAPSHOT
  +-org.jboss.resteasy:resteasy-core:jar:5.0.3.Final:provided
    +-org.jboss.resteasy:resteasy-core-spi:jar:5.0.3.Final:provided
      +-org.apache.logging.log4j:log4j-api:jar:2.13.3:provided
and
+-org.pac4j:resteasy5-pac4j:jar:5.0.1-SNAPSHOT
  +-org.jboss.resteasy:resteasy-core:jar:5.0.3.Final:provided
    +-org.jboss.resteasy:resteasy-core-spi:jar:5.0.3.Final:provided
      +-org.apache.logging.log4j:log4j-core:jar:2.13.3:provided
        +-org.apache.logging.log4j:log4j-api:jar:2.13.3:provided
```

**Comment by leleuj** [comment]
OK. Not big deal here.
